-- Run as your app schema (e.g. APP_USER).

CREATE TABLE documents (
    doc_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR2(400),
    content    CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Webhook target URL. Use an address the DATABASE can reach (not localhost
-- unless Oracle runs on the same machine).
CREATE TABLE webhook_config (
    name  VARCHAR2(60) PRIMARY KEY,
    value VARCHAR2(500)
);

INSERT INTO webhook_config (name, value) VALUES ('url', 'http://192.168.1.10:8000/webhook');
COMMIT;
